---
- name: Preparing system for Ansible
  hosts: all
  gather_facts: false
  become: yes
  vars:
    packages: python3 python3-dev python3-pip python3-netaddr python3-setuptools python3-requests
  pre_tasks:

    - name: Waiting server
      wait_for_connection:
        delay: 15
        timeout: 300
      when: "wait_server is defined and wait_server|bool == True"


    - name: Wait apt ready
      raw: bash -c "while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;"
      changed_when: false

    - name: Install python for Ansible
      register: output
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy {{packages}})"
      changed_when: output.stdout != ""

    - name: Copy key
      raw: 'mkdir -p ~/.ssh && chmod 700 ~/.ssh && grep -qF "{{support_key}}" {{auth_keys_f}} || echo "{{support_key}}" >> {{auth_keys_f}}'
      vars:
        auth_keys_f: ~/.ssh/authorized_keys
