# - name: Detecting public IP
#   uri: url=https://api.ipify.org?format=json return_content=yes body_format=json
#   register: ipify_result

- name: Detecting main ip
  command: "dig {{_domain}} +short"
  register: domain_check_result

- debug:
    msg: "Detect result {{domain_check_result.stdout}}"

- name: Checking DNS
  command: "dig {{item}} +short"
  register: subdomain_check_result
  changed_when: False
  failed_when: "domain_check_result.stdout not in subdomain_check_result.stdout"
  with_items: "{{check_domains}}"
