
##### ##### ##### ##### #####    Logspout    ##### ##### ##### ##### ##### 

- name: Configuring Logspout service
  block:

  - docker_container: name=logspout state=absent
  
  - name: Starting container for Logspout service
    docker_container:
      name: logspout
      hostname: logspout
      image: "{{images.logspout}}"
      labels: "{{docker_band_lbls}}"
      networks: [ { name: "{{docker_net_name}}" } ]
      etc_hosts: "{{etc_hosts}}"
      restart_policy: "{{_restart_policy}}"
      restart: yes
      pull: yes
      recreate: yes
      memory: "100m"
      env: "{{ container_env }}"
      volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
      ports:
        - "{{if_inner}}:{{ports.logspout.http.0}}:{{ports.logspout.http.1}}"
        - "{{if_inner}}:{{ports.logspout.udp.0}}:{{ports.logspout.udp.1}}"
  vars:
    service: logspout
    endpoints:
      loggly: "syslog+tcp://{{_loggly_hostname}}"
      papertrail: "syslog+tls://{{_papertrail_hostname}}"
    env:
      common:
        SYSLOG_HOSTNAME: "{{hostname}}"
        TAIL: 100
      loggly:
        SYSLOG_STRUCTURED_DATA: "{{_loggly_api_key}}@41058 tag=\"Logspout\""
  tags: ['never', 'logspout', 'logger', 'monitoring', 'platform', 'ppart', 'docker-container', 'full']

