---

- name: Adding Docker key for Stable version
  apt_key: >
    keyserver="hkp://p80.pool.sks-keyservers.net:80"
    id="58118E89F3A912897C070ADBF76221572C52609D"

- name: Adding Docker repo for Stable version
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: Installing docker
  apt: update_cache=yes name=docker-engine state=present
